# NBA All-Star Weekend Challenge

Your task...answer the following questions given the dataset given about the NBA All-Star Game from the year 2000 - 2016

Become more familiar with the dataset <a href="https://www.kaggle.com/fmejia21/nba-all-star-game-20002016">here</a>

Once completed, commit this notebook to github and submit the link to the google classroom assignment.

<a href="https://classroom.google.com/u/2/c/NDc4MzEzMjI5Nzla/a/NTE3OTYxNzM2OTNa/details">Google Classroom</a>

# What is the average weight of all players who played during this time?

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

allStar = pd.read_csv('NBA All Stars 2000-2016 - Sheet1.csv')

print(allStar.columns)
allStar

Index(['Year', 'Player', 'Pos', 'HT', 'WT', 'Team', 'Selection Type',
       'NBA Draft Status', 'Nationality'],
      dtype='object')

,Year,Player,Pos,HT,WT,Team,Selection Type,NBA Draft Status,Nationality
0,2016,Stephen Curry,G,6-3,190,Golden State Warriors,Western All-Star Fan Vote Selection,2009 Rnd 1 Pick 7,United States
1,2016,James Harden,SG,6-5,220,Houston Rockets,Western All-Star Fan Vote Selection,2009 Rnd 1 Pick 3,United States
2,2016,Kevin Durant,SF,6-9,240,Golden State Warriors,Western All-Star Fan Vote Selection,2007 Rnd 1 Pick 2,United States
3,2016,Kawhi Leonard,F,6-7,230,San Antonio Spurs,Western All-Star Fan Vote Selection,2011 Rnd 1 Pick 15,United States
4,2016,Anthony Davis,PF,6-11,253,New Orleans Pelicans,Western All-Star Fan Vote Selection,2012 Rnd 1 Pick 1,United States
...,...,...,...,...,...,...,...,...,...
434,2000,Antonio McDyess,F,6-9,245,Denver Nuggets,Western All-Star Coaches Selection,1995 Rnd 1 Pick 2,United States
435,2000,Gary Payton,G,6-4,180,Seattle SuperSonics,Western All-Star Coaches Selection,1990 Rnd 1 Pick 2,United States
436,2000,Rasheed Wallace,FC,6-11,230,Portland Trail Blazers,Western All-Star Coaches Selection,1995 Rnd 1 Pick 4,United States
437,2000,David Robinson,C,7-1,250,San Antonio Spurs,Western All-Star Coaches Selection,1987 Rnd 1 Pick 1,United States
438,2000,Vlade Divac,C,7-1,260,Sacramento Kings,Western All-Star Replacement Selection,1989 Rnd 1 Pick 26,Serbia

In [13]:
allStar.mean()[['WT']]

WT    228.751708
dtype: float64

# What team is represented the most during this time?

In [17]:
allStar.groupby(['Team']).count().sort_values('Year', ascending=False)

,Year,Player,Pos,HT,WT,Selection Type,NBA Draft Status,Nationality
Team,,,,,,,,
Miami Heat,28,28,28,28,28,28,28,28
Boston Celtics,26,26,26,26,26,26,26,26
San Antonio Spurs,25,25,25,25,25,25,25,25
Los Angeles Lakers,25,25,25,25,25,25,25,25
Houston Rockets,20,20,20,20,20,20,20,20
Atlanta Hawks,18,18,18,18,18,18,18,18
Phoenix Suns,18,18,18,18,18,18,18,18
Dallas Mavericks,18,18,18,18,18,18,18,18
Cleveland Cavaliers,17,17,17,17,17,17,17,17
Toronto Raptors,16,16,16,16,16,16,16,16
Detroit Pistons,15,15,15,15,15,15,15,15
Indiana Pacers,15,15,15,15,15,15,15,15
Orlando Magic,14,14,14,14,14,14,14,14
Los Angeles Clippers,14,14,14,14,14,14,14,14
Oklahoma City Thunder,13,13,13,13,13,13,13,13
Washington Wizards,13,13,13,13,13,13,13,13
Minnesota Timberwolves,12,12,12,12,12,12,12,12
New Jersey Nets,12,12,12,12,12,12,12,12
Chicago Bulls,12,12,12,12,12,12,12,12
Philadelphia Sixers,11,11,11,11,11,11,11,11
Sacramento Kings,11,11,11,11,11,11,11,11
Golden State Warriors,11,11,11,11,11,11,11,11
New York Knicks,10,10,10,10,10,10,10,10
Portland Trail Blazers,10,10,10,10,10,10,10,10
New Orleans Hornets,9,9,9,9,9,9,9,9
Utah Jazz,9,9,9,9,9,9,9,9
Denver Nuggets,9,9,9,9,9,9,9,9
Seattle SuperSonics,8,8,8,8,8,8,8,8
Memphis Grizzlies,6,6,6,6,6,6,6,6
Milwaukee Bucks,5,5,5,5,5,5,5,5
New Orleans Pelicans,4,4,4,4,4,4,4,4
Charlotte Hornets,2,2,2,2,2,2,2,2
Brooklyn Nets,2,2,2,2,2,2,2,2
Charlotte Bobcats,1,1,1,1,1,1,1,1

# What draft class is represeted the most during this time?

In [41]:
print('1996 Draft Class has the most players appear in the All-Star')
dclass=allStar.groupby(['NBA Draft Status']).count().sort_values('Player', ascending=False)
dclass.head(30)

1996 Draft Class has the most players appear in the All-Star

,Year,Player,Pos,HT,WT,Team,Selection Type,Nationality
NBA Draft Status,,,,,,,,
1996 Rnd 1 Pick 13,16,16,16,16,16,16,16,16
2003 Rnd 1 Pick 1,13,13,13,13,13,13,13,13
1997 Rnd 1 Pick 1,13,13,13,13,13,13,13,13
1998 Rnd 1 Pick 9,13,13,13,13,13,13,13,13
1995 Rnd 1 Pick 5,12,12,12,12,12,12,12,12
2003 Rnd 1 Pick 5,12,12,12,12,12,12,12,12
2003 Rnd 1 Pick 4,11,11,11,11,11,11,11,11
1998 Rnd 1 Pick 10,10,10,10,10,10,10,10,10
1996 Rnd 1 Pick 1,10,10,10,10,10,10,10,10
2005 Rnd 1 Pick 4,9,9,9,9,9,9,9,9
1996 Rnd 1 Pick 5,9,9,9,9,9,9,9,9
2003 Rnd 1 Pick 3,9,9,9,9,9,9,9,9
2004 Rnd 1 Pick 1,8,8,8,8,8,8,8,8
1992 Rnd 1 Pick 1,8,8,8,8,8,8,8,8
1996 Rnd 1 Pick 15,8,8,8,8,8,8,8,8
2002 Rnd 1 Pick 1,8,8,8,8,8,8,8,8
2007 Rnd 1 Pick 2,8,8,8,8,8,8,8,8
2001 Rnd 1 Pick 10,7,7,7,7,7,7,7,7
1998 Rnd 1 Pick 5,7,7,7,7,7,7,7,7
1994 Rnd 1 Pick 2,7,7,7,7,7,7,7,7
1997 Rnd 1 Pick 9,7,7,7,7,7,7,7,7
2001 Rnd 1 Pick 28,6,6,6,6,6,6,6,6
2008 Rnd 1 Pick 4,6,6,6,6,6,6,6,6
1996 Rnd 1 Pick 17,6,6,6,6,6,6,6,6
2001 Rnd 1 Pick 3,6,6,6,6,6,6,6,6
2002 Rnd 1 Pick 9,6,6,6,6,6,6,6,6
2009 Rnd 1 Pick 1,5,5,5,5,5,5,5,5
2009 Rnd 1 Pick 3,5,5,5,5,5,5,5,5
2006 Rnd 1 Pick 2,5,5,5,5,5,5,5,5
1997 Rnd 1 Pick 3,5,5,5,5,5,5,5,5

# Are foriegn players more prevalent in the All-Star Game during this time?

In [40]:
pnationality=allStar.groupby(['Player','Nationality']).count().sort_values('Nationality', ascending=True)
pnationality.head(30)

,,Year,Pos,HT,WT,Team,Selection Type,NBA Draft Status
Player,Nationality,,,,,,,
Manu Ginobili,Argentina,2,2,2,2,2,2,2
Jamaal Magloire,Canada,1,1,1,1,1,1,1
Steve Nash,Canada\nSouth Africa,8,8,8,8,8,8,8
Yao Ming,China,8,8,8,8,8,8,8
Dikembe Mutombo,Democratic Republic of the Congo,2,2,2,2,2,2,2
Al Horford,Dominican Republic\nUnited States,4,4,4,4,4,4,4
Luol Deng,England\nSouth Sudan,2,2,2,2,2,2,2
Tony Parker,France,6,6,6,6,6,6,6
Joakim Noah,France\nUnited States,2,2,2,2,2,2,2
Dirk Nowitzki,Germany,13,13,13,13,13,13,13
Carlos Boozer,Germany\nUnited States,2,2,2,2,2,2,2
Giannis Antetokounmpo,Greece\nNigeria,1,1,1,1,1,1,1
Zydrunas Ilgauskas,Lithuania,2,2,2,2,2,2,2
Andrei Kirilenko,Russia,1,1,1,1,1,1,1
Vlade Divac,Serbia,1,1,1,1,1,1,1
Peja Stojakovic,Serbia\nGreece,3,3,3,3,3,3,3
Pau Gasol,Spain,6,6,6,6,6,6,6
Marc Gasol,Spain,3,3,3,3,3,3,3
Mehmet Okur,Turkey,1,1,1,1,1,1,1
Michael Redd,United States,1,1,1,1,1,1,1
Michael Jordan,United States,2,2,2,2,2,2,2
Michael Finley,United States,1,1,1,1,1,1,1
Metta World Peace,United States,1,1,1,1,1,1,1
Amar'e Stoudemire,United States,6,6,6,6,6,6,6
Andre Drummond,United States,1,1,1,1,1,1,1
LeBron James,United States,13,13,13,13,13,13,13
Latrell Sprewell,United States,1,1,1,1,1,1,1
Antonio Davis,United States,1,1,1,1,1,1,1
Kyle Lowry,United States,3,3,3,3,3,3,3
Kyle Korver,United States,1,1,1,1,1,1,1

# How often are the Western All-Stars voted in by fans?

In [46]:
print('Fans voted for Western All-Stars 119 times')
confStars=allStar.groupby(['Selection Type']).count().sort_values('Selection Type', ascending=False)
confStars.head(50)

Fans voted for Western All-Stars 119 times

,Year,Player,Pos,HT,WT,Team,NBA Draft Status,Nationality
Selection Type,,,,,,,,
Western All-Star Replacement Selection,15,15,15,15,15,15,15,15
Western All-Star Fan Vote Selection,85,85,85,85,85,85,85,85
Western All-Star Coaches Selection,119,119,119,119,119,119,119,119
Eastern All-Star Replacement Selection,16,16,16,16,16,16,16,16
Eastern All-Star Fan Vote Selection,85,85,85,85,85,85,85,85
Eastern All-Star Coaches Selection,119,119,119,119,119,119,119,119

# How many times does Steph Curry make the All-Star game during this time period?

In [58]:
print('Steph made the All-Star Team 4 times from 2009-2016')
steph=allStar.groupby(['Player']).count().sort_values('Selection Type', ascending=False)
steph.head(50)

Steph made the All-Star Team 4 times from 2009-2016

,Year,Pos,HT,WT,Team,Selection Type,NBA Draft Status,Nationality
Player,,,,,,,,
Kobe Bryant,16,16,16,16,16,16,16,16
Tim Duncan,13,13,13,13,13,13,13,13
LeBron James,13,13,13,13,13,13,13,13
Dirk Nowitzki,13,13,13,13,13,13,13,13
Kevin Garnett,12,12,12,12,12,12,12,12
Dwyane Wade,12,12,12,12,12,12,12,12
Chris Bosh,11,11,11,11,11,11,11,11
Paul Pierce,10,10,10,10,10,10,10,10
Allen Iverson,10,10,10,10,10,10,10,10
Chris Paul,9,9,9,9,9,9,9,9
Carmelo Anthony,9,9,9,9,9,9,9,9
Ray Allen,9,9,9,9,9,9,9,9
Dwight Howard,8,8,8,8,8,8,8,8
Shaquille O'Neal,8,8,8,8,8,8,8,8
Yao Ming,8,8,8,8,8,8,8,8
Steve Nash,8,8,8,8,8,8,8,8
Kevin Durant,8,8,8,8,8,8,8,8
Jason Kidd,7,7,7,7,7,7,7,7
Joe Johnson,7,7,7,7,7,7,7,7
Vince Carter,7,7,7,7,7,7,7,7
Tracy McGrady,7,7,7,7,7,7,7,7
Pau Gasol,6,6,6,6,6,6,6,6
Tony Parker,6,6,6,6,6,6,6,6
Jermaine O'Neal,6,6,6,6,6,6,6,6
Amar'e Stoudemire,6,6,6,6,6,6,6,6
Russell Westbrook,6,6,6,6,6,6,6,6
Blake Griffin,5,5,5,5,5,5,5,5
Chauncey Billups,5,5,5,5,5,5,5,5
LaMarcus Aldridge,5,5,5,5,5,5,5,5
James Harden,5,5,5,5,5,5,5,5
Kyrie Irving,4,4,4,4,4,4,4,4
Paul Millsap,4,4,4,4,4,4,4,4
Kevin Love,4,4,4,4,4,4,4,4
Paul George,4,4,4,4,4,4,4,4
Al Horford,4,4,4,4,4,4,4,4
John Wall,4,4,4,4,4,4,4,4
Anthony Davis,4,4,4,4,4,4,4,4
Stephen Curry,4,4,4,4,4,4,4,4
Rajon Rondo,4,4,4,4,4,4,4,4
Shawn Marion,4,4,4,4,4,4,4,4
Ben Wallace,4,4,4,4,4,4,4,4
Gilbert Arenas,3,3,3,3,3,3,3,3
Jimmy Butler,3,3,3,3,3,3,3,3
Steve Francis,3,3,3,3,3,3,3,3
Klay Thompson,3,3,3,3,3,3,3,3
Brandon Roy,3,3,3,3,3,3,3,3
Kyle Lowry,3,3,3,3,3,3,3,3
Richard Hamilton,3,3,3,3,3,3,3,3
DeMarcus Cousins,3,3,3,3,3,3,3,3
DeMar DeRozan,3,3,3,3,3,3,3,3

# How many Shooting Gaurds have made the All-Star game during this time?

In [62]:
print('57 SHooting Guards made the All-Star during this time')
sg=allStar.groupby(['Pos']).count().sort_values('Player', ascending=False)
sg.head(50)

57 SHooting Guards made the All-Star during this time

     Year  Player  HT  WT  Team  Selection Type  NBA Draft Status  Nationality
Pos
G      72      72  72  72    72              72                72           72
FC     61      61  61  61    61              61                61           61
PF     57      57  57  57    57              57                57           57
SG     57      57  57  57    57              57                57           57
C      50      50  50  50    50              50                50           50
F      45      45  45  45    45              45                45           45
PG     36      36  36  36    36              36                36           36
SF     35      35  35  35    35              35                35           35
GF     22      22  22  22    22              22                22           22
F-C     3       3   3   3     3               3                 3            3
G-F     1       1   1   1     1               1                 1            1

# How many Chicago Bulls players have made the All-Star Game during this time period?

In [64]:
print('Chicago Bulls players made the All-Star 12 times during this time')
bulls=allStar.groupby(['Team']).count().sort_values('Player', ascending=False)
bulls.head(33)

Chicago Bulls players made the All-Star 12 times during this time

,Year,Player,Pos,HT,WT,Selection Type,NBA Draft Status,Nationality
Team,,,,,,,,
Miami Heat,28,28,28,28,28,28,28,28
Boston Celtics,26,26,26,26,26,26,26,26
San Antonio Spurs,25,25,25,25,25,25,25,25
Los Angeles Lakers,25,25,25,25,25,25,25,25
Houston Rockets,20,20,20,20,20,20,20,20
Atlanta Hawks,18,18,18,18,18,18,18,18
Phoenix Suns,18,18,18,18,18,18,18,18
Dallas Mavericks,18,18,18,18,18,18,18,18
Cleveland Cavaliers,17,17,17,17,17,17,17,17
Toronto Raptors,16,16,16,16,16,16,16,16
Detroit Pistons,15,15,15,15,15,15,15,15
Indiana Pacers,15,15,15,15,15,15,15,15
Orlando Magic,14,14,14,14,14,14,14,14
Los Angeles Clippers,14,14,14,14,14,14,14,14
Oklahoma City Thunder,13,13,13,13,13,13,13,13
Washington Wizards,13,13,13,13,13,13,13,13
Minnesota Timberwolves,12,12,12,12,12,12,12,12
New Jersey Nets,12,12,12,12,12,12,12,12
Chicago Bulls,12,12,12,12,12,12,12,12
Philadelphia Sixers,11,11,11,11,11,11,11,11
Sacramento Kings,11,11,11,11,11,11,11,11
Golden State Warriors,11,11,11,11,11,11,11,11
New York Knicks,10,10,10,10,10,10,10,10
Portland Trail Blazers,10,10,10,10,10,10,10,10
New Orleans Hornets,9,9,9,9,9,9,9,9
Utah Jazz,9,9,9,9,9,9,9,9
Denver Nuggets,9,9,9,9,9,9,9,9
Seattle SuperSonics,8,8,8,8,8,8,8,8
Memphis Grizzlies,6,6,6,6,6,6,6,6
Milwaukee Bucks,5,5,5,5,5,5,5,5
New Orleans Pelicans,4,4,4,4,4,4,4,4
Charlotte Hornets,2,2,2,2,2,2,2,2
Brooklyn Nets,2,2,2,2,2,2,2,2